name = "Org"
uuid = "587fedb0-ad84-11e9-2bd6-d15ea4be1f9e"
authors = ["TEC <tec@tecosaur.com> and contributors"]
version = "0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
